Add darwin (Mac OS) to the list of supported systems in nix flake (#4)
* Add darwin (Mac OS) to the list of supported systems in nix flake

* Replace nix flake check with sequence of calls to cabal

Co-authored-by: Lukasz Golebiewski <lukasz.golebiewski@gmail.com>

Commands like 'nix flake check' and 'nix flake show' only work with for a single
system builds in flakes. For example when running a 'nix flake check' on a x86_64-linux
system, when x86_64-darwin is added to the lists of systems, the command will fail with
following Error

```
error: a 'x86_64-darwin' with features {} is required to build '/nix/store/sap5h3aqfpmhm9vgd4c3lmdfbaa4rxh6-alex-3.2.4-r1-src.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, nixos-test}
```